### PR TITLE
Fix spanish lessons creation

### PR DESCRIPTION
**Pull request by Canx**
Added spanish accentuated vowels in 'isLetter' function, and removed redundant characters 'ç' and 'ñ' in allowed_chars.

### CODE REVIEW

**Comment by jl2035** [comment]
I hope you have tested your changes, because I'm auto-merging the pull request.

I didn't know people still use Mootyper.

**Comment by Canx** [comment]
Hi, it was my first pull request so maybe I was too excited and forgot to add same characters in "eedit.php".

I'm still trying to understand the code. I would love to fix or help to fix #7.

**Comment by jl2035** [comment]
hm.. those ticks, ` and ´ are real pain.. so i got stuck at #7

if some part of the code is difficult to understand, please ask.. the code is quite messy at some points

**Comment by Canx** [comment]
Hi, trying here to understand code dependencies before attempting to solve
this...

https://drive.google.com/file/d/0B3EJYdO7D5CaNVhUUEZhb2k1TGc/view





2015-10-13 1:11 GMT+02:00 jl2035 <notifications@github.com>:

**Pull request merged**
